#!/bin/bash

# look for users with a local display
USRX=($(who | sed -n -e 's/^\([^ ]*\) *pts\/[0-9]* *[-0-9: ]*(\(:[0-9]*\))$/\1 \2/gp' | sort | uniq | sed -n 1p))

# ${USRX[0]} == user ${USRX[1]} == display
su ${USRX[0]} -c "DISPLAY=${USRX[1]} shuttlepro /dev/input/by-id/usb-Contour_Design_ShuttlePRO_v2-event-if00"
